production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    solr_home: #{Rails.root}/solr
    max_memory: 512M

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    solr_home: #{Rails.root}/solr